# Generated by Django 3.2.6 on 2021-12-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
