# Generated by Django 3.2.6 on 2021-12-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customusermodel_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='avatar',
        ),
    ]
