# Generated by Django 3.2.4 on 2021-12-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_customusermodel_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='images/avatar'),
        ),
    ]
