# Generated by Django 3.2.4 on 2021-12-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_customusermodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
