# Generated by Django 3.2.6 on 2021-12-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_customusermodel_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='avatar',
        ),
    ]
