# Generated by Django 3.2.6 on 2021-12-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Olkenin adi:')),
                ('flag', models.ImageField(upload_to='country_pictures')),
            ],
        ),
    ]
