# Generated by Django 3.2.6 on 2021-12-07 14:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kategoriyanin adi')),
            ],
        ),
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Rayon Adi:')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Xidmetin adi:')),
            ],
        ),
        migrations.CreateModel(
            name='TourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name='Turun adi:')),
                ('detail', models.TextField(verbose_name='Turun detali:')),
                ('finished_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_fin', to='enterprises.districtmodel', verbose_name='Bitis bolgesi')),
                ('started_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_start', to='enterprises.districtmodel', verbose_name='Baslangic bolgesi')),
                ('where_tour_will_pass', models.ManyToManyField(related_name='tour_pass', to='enterprises.DistrictModel', verbose_name='Haralardan kececek:')),
            ],
        ),
        migrations.CreateModel(
            name='EnterpriseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Muessise adi:')),
                ('about', models.TextField(verbose_name='Muessise haqqinda:')),
                ('address', models.CharField(max_length=150)),
                ('category', models.ManyToManyField(related_name='enterprises', to='enterprises.CategoryModel')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterprises', to='enterprises.countrymodel', verbose_name='Olke')),
                ('services', models.ManyToManyField(related_name='enterprises', to='enterprises.ServiceModel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=1000, verbose_name='Commentin Mezmunu:')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='enterprises.enterprisemodel')),
            ],
        ),
    ]
