# Generated by Django 3.2.4 on 2021-12-07 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprises', '0003_auto_20211207_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprisemodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Mesulinsan', to=settings.AUTH_USER_MODEL, verbose_name='sirketler'),
        ),
    ]
