# Generated by Django 3.2.4 on 2021-12-07 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enterprises', '0005_alter_enterprisemodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisemodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sirketler', to=settings.AUTH_USER_MODEL, verbose_name='Mesul sexs(email)'),
        ),
    ]
