# Generated by Django 3.2.4 on 2021-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0008_remove_enterprisemodel_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisemodel',
            name='authorized_person',
            field=models.CharField(max_length=100, null=True, verbose_name='Mesul sexsin Adi'),
        ),
        migrations.AlterField(
            model_name='enterprisemodel',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Muessise adi'),
        ),
    ]
