# Generated by Django 3.2.6 on 2021-12-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0009_auto_20211211_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisemodel',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Muessise haqqinda:'),
        ),
        migrations.AlterField(
            model_name='enterprisemodel',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RemoveField(
            model_name='enterprisemodel',
            name='category',
        ),
        migrations.AddField(
            model_name='enterprisemodel',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='enterprisemodel',
            name='services',
        ),
        migrations.AddField(
            model_name='enterprisemodel',
            name='services',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
