# Generated by Django 3.2.6 on 2021-12-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0010_auto_20211221_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisemodel',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisemodel',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enterprisemodel',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Olke'),
        ),
        migrations.AlterField(
            model_name='enterprisemodel',
            name='services',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
