# Generated by Django 3.2.6 on 2021-12-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprises', '0011_auto_20211221_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprisemodel',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
